[tool.poetry]
name = "pydme"
version = "0.2.0"
description = "Hook into the Dolphin emulator and manipulate the memory"
readme = "README.md"
authors = ["Maximillian Strand <maximillian.strand@protonmail.com>"]
repository = "https://gitlab.com/OpenDisrupt/pydme"

[tool.poetry.dependencies]
python = "^3.9"
dolphin-memory-engine = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
