[tool.poetry]
name = "cse546backend"
version = "0.1.0"
description = ""
authors = ["adityakrshnn <adityakrshnn@gmail.com>"]

packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = {extras = ["all"], version = "^0.74.1"}

[tool.poetry.scripts]
start = "src.main:start"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
