[project]
name = "fast_unit"

[tool.poetry]
name = "fast_unit"
version = "0.5.1"
description = ""
authors = ["ethan <ethan.chapman0@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.10"
maturin = "^0.12.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"
