[tool.poetry]
authors = ["Christopher Ritsen <chris.ritsen@gmail.com>"]
classifiers = ["Topic :: Multimedia :: Sound/Audio"]
description = "List, configure, and control Dante network audio devices without Dante Controller"
documentation = "https://github.com/chris-ritsen/network-audio-controller/wiki"
include = ["LICENSE"]
keywords = ["audinate", "audio", "cli", "dante", "network"]
license = "Unlicense"
name = "netaudio"
readme = "README.md"
repository = "https://github.com/chris-ritsen/network-audio-controller"
version = "0.0.10"

[tool.poetry.dependencies]
cleo = "^0.8.1"
netifaces = "^0.11.0"
python = "^3.7"
twisted = "^22.1.0"
zeroconf = "^0.38.3"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
pipx = "^1.0.0"
pylint = "^2.12.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
netaudio = "netaudio:main"
