
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T18:52:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a5dd84eacbba6580561f8299ae852b4e6d40e4f",
 "version": "v2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
