
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-14T10:00:43-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "be8c743f66777770c4fc2780c56f6fd9a216f301",
 "version": "5.0.0-a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
