
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-23T22:39:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dcf53306eb3f15b64eaf0fc0a9460bcf2b178f04",
 "version": "0.0.65.post0.dev149"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
