
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-26T18:51:04-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "95af658d2f939f27389d795b3891ddc7e96c00a0",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
