[tool.poetry]
name = "pybeast"
version = "0.2.0"
description = ""
authors = ["Wytamma Wirth <wytamma.wirth@me.com>"]
readme = "README.md"

[tool.poetry.scripts]
pybeast = "pybeast.main:app"

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0"
typer = "^0.4.0"
dynamic-beast = "^1.8.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
