[tool.poetry]
name = "chocs_middleware.cache"
version = "1.0.0"
description = "Middleware to simplify caching your resources."
authors = [
    "Dawid Kraczkowski <dawid.kraczkowski@gmail.com>"
]
license = "MIT"
readme = "README.md"
packages = [
  { include = "chocs_middleware" }
]
homepage = "https://github.com/kodemore/chocs-cache"
repository = "https://github.com/kodemore/chocs-cache"
documentation = "https://github.com/kodemore/chocs-cache"

keywords = ["cache", "chocs", "http", "middleware"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]

# Requirements
[tool.poetry.dependencies]
python = "^3.8"
chocs = "^1.5.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-cov = "^3.0"
black = "22.1.0"
isort = "^5.6.4"
mypy = "^0.931"
pylint = "^2.7.2"
