
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-02T12:48:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "77d5c61e85febf7876969d95f790aec7368eacd1",
 "version": "0.9.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
