VERSION_YEAR = 2022
VERSION_MONTH = int('02')
VERSION_DAY = int('27')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('00')
MAJOR_VERSION = 1
MINOR_VERSION = 7
PATCH_VERSION = 202202270800
version_date = '2022/02/27 08:00'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
