# MONGODB SETTING
MONGO_HOST = 'localhost'
MONGO_PORT = 27017
MONGO_USERNAME = None
MONGO_PASSWORD = None
MONGO_DATABASE = None
MONGO_COLLECTION = None
MONGO_CONN_TIMEOUT = 30
MONGO_CONN_RETRIES = 5

# MYSQL SETTING
MYSQL_HOST = 'localhost'
MYSQL_PORT = 3306
MYSQL_USERNAME = None
MYSQL_PASSWORD = None
MYSQL_DATABASE = None
MYSQL_COLLECTION = None
MYSQL_CONN_TIMEOUT = 30
MYSQL_CONN_RETRIES = 5

PANDAS_ENCODING = 'utf_8_sig'
TIME_ZONE = 'Asia/Shanghai'

THREAD_POOL_MAX_WORKERS = 8
MONGO_POOL_MAX_WORKERS = 200

ECHO_INFO = '{}[+] {} exported successfully → {}'

IGNORE_TYPE = (str, int, float, bool)
