
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-01T15:37:11-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "c27183cfdafc00313ebaab308efe46e51d6035dc",
 "version": "2.4.0.dev20220302"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
