[tool.poetry]
name = "poc_artifactory_gitlab_lib"
version = "0.1.0"
description = "Gitlab-CI POC project."
authors = ["Pierre-Yves Gillier <pierre-yves.gillier@jellysmack.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
