[tool.poetry]
name = "python-trovo"
version = "0.1.5"
description = "A Python wrapper for the Trovo API"
authors = ["P. R. d. O. <liquid.query960@4wrd.cc>"]
license = "GPL-3.0-only"
packages = [
	{ include = "trovoApi" }
]
exclude = [
	"**/*.nix",
	"flake.lock",
	"TODO.md"
]
readme = "README.md"
repository = "https://codeberg.org/wolfangaukang/python-trovo"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pycodestyle = "^2.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
