[tool.poetry]
name = "apirunner_html"
version = "1.1.2"
description = "The HTML Report for Python api testing Base on PyTestReport and pytest_html"
authors = [ "ylfeng"]
license = "Apache-2.0"

[tool.poetry.dependencies]
ansi2html = "1.6.0"
Flask = "1.1.2"
Jinja2 = "2.11.2"
MarkupSafe = "0.23"
pytest_html = "2.1.1"

[tool.poetry.scripts]
apirunner_html = "apirunner_html:shell"

[tool.poetry.plugins."pytest11"]
"apirunner_html" = "apirunner_html.report"

[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"
