
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T11:35:05-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "32519e38c67cafd1d43d8b6ca2567aaaebf8a7ff",
 "version": "4.9.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
