
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <frc\commands\Command.h>

#include <wpi/sendable/SendableBuilder.h>
#include <frc/commands/CommandGroup.h>



#include <rpygen/wpi__Sendable.hpp>

namespace rpygen {

using namespace frc;


template <typename CfgBase>
using PyTrampolineCfgBase_frc__Command =
    PyTrampolineCfg_wpi__Sendable<
CfgBase
>;

template <typename CfgBase = EmptyTrampolineCfg>
struct PyTrampolineCfg_frc__Command :
    PyTrampolineCfgBase_frc__Command< CfgBase>
{
    using Base = frc::Command;

    using override_base_InitSendable_RTSendableBuilder = frc::Command;
    using override_base_Initialize_v = frc::Command;
    using override_base_Execute_v = frc::Command;
    using override_base_IsFinished_v = frc::Command;
    using override_base_End_v = frc::Command;
    using override_base_Interrupted_v = frc::Command;
    using override_base__Initialize_v = frc::Command;
    using override_base__Interrupted_v = frc::Command;
    using override_base__Execute_v = frc::Command;
    using override_base__End_v = frc::Command;
    using override_base__Cancel_v = frc::Command;
};


template <typename PyTrampolineBase, typename PyTrampolineCfg>
using PyTrampolineBase_frc__Command =
    PyTrampoline_wpi__Sendable<
        PyTrampolineBase
        
        , PyTrampolineCfg
    >
;

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_frc__Command : PyTrampolineBase_frc__Command<PyTrampolineBase, PyTrampolineCfg> {
    using PyTrampolineBase_frc__Command<PyTrampolineBase, PyTrampolineCfg>::PyTrampolineBase_frc__Command;



#ifndef RPYGEN_DISABLE_InitSendable_RTSendableBuilder
    void InitSendable(wpi::SendableBuilder& builder) override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_InitSendable_RTSendableBuilder;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "initSendable", builder);
        return CxxCallBase::InitSendable(builder);
    }
#endif

#ifndef RPYGEN_DISABLE_Initialize_v
    void Initialize() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_Initialize_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "initialize", );
        return CxxCallBase::Initialize();
    }
#endif

#ifndef RPYGEN_DISABLE_Execute_v
    void Execute() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_Execute_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "execute", );
        return CxxCallBase::Execute();
    }
#endif

#ifndef RPYGEN_DISABLE_IsFinished_v
    bool IsFinished() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        RPYBUILD_OVERRIDE_PURE_NAME(Command, PYBIND11_TYPE(bool), LookupBase,
            "isFinished", IsFinished, );
    }
#endif

#ifndef RPYGEN_DISABLE_End_v
    void End() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_End_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "end", );
        return CxxCallBase::End();
    }
#endif

#ifndef RPYGEN_DISABLE_Interrupted_v
    void Interrupted() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_Interrupted_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "interrupted", );
        return CxxCallBase::Interrupted();
    }
#endif

#ifndef RPYGEN_DISABLE__Initialize_v
    void _Initialize() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base__Initialize_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "_initialize", );
        return CxxCallBase::_Initialize();
    }
#endif

#ifndef RPYGEN_DISABLE__Interrupted_v
    void _Interrupted() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base__Interrupted_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "_interrupted", );
        return CxxCallBase::_Interrupted();
    }
#endif

#ifndef RPYGEN_DISABLE__Execute_v
    void _Execute() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base__Execute_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "_execute", );
        return CxxCallBase::_Execute();
    }
#endif

#ifndef RPYGEN_DISABLE__End_v
    void _End() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base__End_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "_end", );
        return CxxCallBase::_End();
    }
#endif

#ifndef RPYGEN_DISABLE__Cancel_v
    void _Cancel() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base__Cancel_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "_cancel", );
        return CxxCallBase::_Cancel();
    }
#endif


#ifndef RPYBLD_DISABLE_SetTimeout_Tsecond_t
  #ifndef RPYBLD_UDISABLE_frc__Command_SetTimeout
    using frc::Command::SetTimeout;
    #define RPYBLD_UDISABLE_frc__Command_SetTimeout
  #endif
#endif
#ifndef RPYBLD_DISABLE_KIsTimedOut_v
  #ifndef RPYBLD_UDISABLE_frc__Command_IsTimedOut
    using frc::Command::IsTimedOut;
    #define RPYBLD_UDISABLE_frc__Command_IsTimedOut
  #endif
#endif
#ifndef RPYBLD_DISABLE_AssertUnlocked_Tstring_view
  #ifndef RPYBLD_UDISABLE_frc__Command_AssertUnlocked
    using frc::Command::AssertUnlocked;
    #define RPYBLD_UDISABLE_frc__Command_AssertUnlocked
  #endif
#endif
#ifndef RPYBLD_DISABLE_SetParent_PTCommandGroup
  #ifndef RPYBLD_UDISABLE_frc__Command_SetParent
    using frc::Command::SetParent;
    #define RPYBLD_UDISABLE_frc__Command_SetParent
  #endif
#endif
#ifndef RPYBLD_DISABLE_KIsParented_v
  #ifndef RPYBLD_UDISABLE_frc__Command_IsParented
    using frc::Command::IsParented;
    #define RPYBLD_UDISABLE_frc__Command_IsParented
  #endif
#endif
#ifndef RPYBLD_DISABLE_ClearRequirements_v
  #ifndef RPYBLD_UDISABLE_frc__Command_ClearRequirements
    using frc::Command::ClearRequirements;
    #define RPYBLD_UDISABLE_frc__Command_ClearRequirements
  #endif
#endif


};

}; // namespace rpygen
