[tool.poetry]
name = "eagerx_examples"
version = "0.1.3"
license = "Apache2.0"
description = "Code examples of EAGERx."
authors = ["Bas van der Heijden <d.s.vanderheijden@tudelft.nl>", "Jelle Luijkx <j.d.luijkx@tudelft.nl>"]
homepage = "https://github.com/eager-dev/eagerx"
repository = "https://github.com/eager-dev/eagerx_packages"
documentation = "https://eagerx.readthedocs.io/en/master/"
include = ["data/with_actions.h5"]

[tool.poetry.dependencies]
python = "^3.6.2"
eagerx = "^0.1.2"
h5py = "^2.9.0"
stable-baselines3 = "1.1.0"
pyglet = "^1.5.21"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
pytest = "^5.2"
pytest-cov = "^3.0.0"
flake8 = "^4.0.1"
flake8-bugbear = "^22.1.11"
eagerx = {path = "../../eagerx", develop = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
