[tool.poetry]
name = "kaeru"
version = "0.2.3"
description = ""
authors = ["faith <jamienibtong@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
SQLAlchemy = {extras = ["asyncio"], version = "^1.4.25"}
aiosqlite = "^0.17.0"
aiohttp = "^3.7.4"
cchardet = "^2.1.7"
aiodns = "^3.0.0"
greenlet = "^1.1.2"
alright = "^1.7"
webwhatsapi = "^2.0.5"

[tool.poetry.dev-dependencies]
black = {version = "^21.9b0", allow-prereleases = true}

[tool.pyright]
venvPath = ["./"]
venv = [".venv"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
kaeru = 'kaeru.cli:run'
