
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <frc\buttons\NetworkButton.h>

#include <wpi/sendable/SendableBuilder.h>
#include <frc/buttons/Trigger.h>
#include <frc/commands/Command.h>
#include <frc/commands/CommandGroup.h>



#include <rpygen/frc__Button.hpp>

namespace rpygen {

using namespace frc;


template <typename CfgBase>
using PyTrampolineCfgBase_frc__NetworkButton =
    PyTrampolineCfg_frc__Button<
CfgBase
>;

template <typename CfgBase = EmptyTrampolineCfg>
struct PyTrampolineCfg_frc__NetworkButton :
    PyTrampolineCfgBase_frc__NetworkButton< CfgBase>
{
    using Base = frc::NetworkButton;

    using override_base_Get_v = frc::NetworkButton;
};


template <typename PyTrampolineBase, typename PyTrampolineCfg>
using PyTrampolineBase_frc__NetworkButton =
    PyTrampoline_frc__Button<
        PyTrampolineBase
        
        , PyTrampolineCfg
    >
;

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_frc__NetworkButton : PyTrampolineBase_frc__NetworkButton<PyTrampolineBase, PyTrampolineCfg> {
    using PyTrampolineBase_frc__NetworkButton<PyTrampolineBase, PyTrampolineCfg>::PyTrampolineBase_frc__NetworkButton;



#ifndef RPYGEN_DISABLE_Get_v
    bool Get() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_Get_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(bool), LookupBase,
            "get", );
        return CxxCallBase::Get();
    }
#endif




};

}; // namespace rpygen
