
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <frc\buttons\ButtonScheduler.h>

#include <wpi/sendable/SendableBuilder.h>
#include <frc/buttons/Trigger.h>
#include <frc/commands/Command.h>
#include <frc/commands/CommandGroup.h>




namespace rpygen {

using namespace frc;



template <typename CfgBase = EmptyTrampolineCfg>
struct PyTrampolineCfg_frc__ButtonScheduler :
    CfgBase
{
    using Base = frc::ButtonScheduler;

    using override_base_Execute_v = frc::ButtonScheduler;
};


template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_frc__ButtonScheduler : PyTrampolineBase, virtual py::trampoline_self_life_support {
    using PyTrampolineBase::PyTrampolineBase;



#ifndef RPYGEN_DISABLE_Execute_v
    void Execute() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        RPYBUILD_OVERRIDE_PURE_NAME(ButtonScheduler, PYBIND11_TYPE(void), LookupBase,
            "execute", Execute, );
    }
#endif



    using frc::ButtonScheduler::m_pressedLast;
    using frc::ButtonScheduler::m_button;
    using frc::ButtonScheduler::m_command;

};

}; // namespace rpygen
