[tool.poetry]
name = "flypper-sqlalchemy"
version = "0.1.6"
description = "Feature flags, with a GUI - SQL Alchemy backend"
documentation = "https://github.com/nicoolas25/flypper-sqlalchemy"
repository = "https://github.com/nicoolas25/flypper-sqlalchemy"
authors = ["Nicolas Zermati <nicoolas25@gmail.com>"]
readme = "README.md"
packages = [
  { include = "flypper_sqlalchemy" },
  { include = "README.md" },
  { include = "LICENSE" },
]

[tool.poetry.dependencies]
python = "^3.7"
flypper = "^0.1.6"
SQLAlchemy = "^1.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.910"
sqlalchemy-stubs = "^0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
