
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-23T17:03:33+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c4a847e081758275af730a531520cdb82e5be4b",
 "version": "2.9.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
