[tool.poetry]
name = "mg_crp"
version = "0.0.2"
description = "Создание файлов конфигураци"
repository = "https://github.com/denisxab/mg_crp.git"
documentation = "https://mg_crp.readthedocs.io/ru/latest/index.html"
authors = ["Denis Kustov <denis-kustov@rambler.ru>"]
readme = "README.md"
exclude = [
    "mg_crp/.idea",
    "mg_crp/venv",
    "mg_crp/.git",
    "mg_crp/.gitignore",
    "mg_crp/test",
    "mg_crp/Makefile"
]

[tool.poetry.dependencies]
python = "^3.10"
pycryptodomex = "^3.14.1"


[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
Nuitka = "^0.6.19"
Sphinx = "^4.4.0"
sphinx-autobuild = "^2021.3.14"
sphinx-rtd-theme = "^1.0.0"
m2r2 = "^0.3.2"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

