description: Income sources that count as income for school meal subsidies.

values:
  2009-01-01:
    - employment_income
    - self_employment_income
    - dividend_income
    - interest_income
    - gi_cash_assistance

metadata:
  reference:
    - title: United States Code, Title 7, Subsection 273.9(b)(1)
      href: https://www.law.cornell.edu/cfr/text/7/273.9#b_1
