[tool.poetry]
name = "py-s2s"
version = "21.02.28"
description = "Python service to service communication over rabbitmq ephemeral queues"
authors = ["Skyler Lewis <skyler@hivewire.co>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://hivewire.co"
repository = "https://gitlab.com/hivewire/open-source/py-s2s"
documentation = "https://gitlab.com/hivewire/open-source/py-s2s/-/blob/master/README.md"
keywords = ["Service-to-Service",
            "aio-pika",
            "asyncio",
            "rabbitmq",
            "microservices"]


[tool.poetry.dependencies]
python = "^3.8"
aio-pika = "^7.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
