[package]
name = "hash-ring-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "hash_ring_rs"
crate-type = ["cdylib"]

[dependencies]
sha2 = "0.10.1"
pyo3 = { version = "0.15.1", features = ["extension-module"] }
