[tool.poetry]
name = "telegramz"
version = "0.0.0.0.1"
description = ""
authors = ["saner99 <it@saner99.ru>"]

readme = 'README.md'


packages = [{ include = "tgz", from = "telegramz" }]

[tool.poetry.dependencies]
python = "^3.6"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


#[tool.poetry.scripts]
#ctprint = 'ctprint:main'