
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-02T11:43:38-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "53dfff86207fa3cbf6ecbf9f69398c82d0a060ef",
 "version": "0.0.84"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
