# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['rob', 'robolson']

package_data = \
{'': ['*'],
 'rob': ['.git/*',
         '.git/hooks/*',
         '.git/info/*',
         '.git/logs/*',
         '.git/logs/refs/heads/*',
         '.git/logs/refs/remotes/origin/*',
         '.git/objects/03/*',
         '.git/objects/04/*',
         '.git/objects/05/*',
         '.git/objects/06/*',
         '.git/objects/08/*',
         '.git/objects/0a/*',
         '.git/objects/0b/*',
         '.git/objects/0c/*',
         '.git/objects/0f/*',
         '.git/objects/11/*',
         '.git/objects/13/*',
         '.git/objects/15/*',
         '.git/objects/18/*',
         '.git/objects/19/*',
         '.git/objects/1a/*',
         '.git/objects/1d/*',
         '.git/objects/21/*',
         '.git/objects/22/*',
         '.git/objects/24/*',
         '.git/objects/29/*',
         '.git/objects/2a/*',
         '.git/objects/2b/*',
         '.git/objects/2c/*',
         '.git/objects/2d/*',
         '.git/objects/2f/*',
         '.git/objects/30/*',
         '.git/objects/32/*',
         '.git/objects/35/*',
         '.git/objects/38/*',
         '.git/objects/39/*',
         '.git/objects/3a/*',
         '.git/objects/3c/*',
         '.git/objects/3d/*',
         '.git/objects/3f/*',
         '.git/objects/40/*',
         '.git/objects/41/*',
         '.git/objects/42/*',
         '.git/objects/45/*',
         '.git/objects/48/*',
         '.git/objects/49/*',
         '.git/objects/4a/*',
         '.git/objects/4d/*',
         '.git/objects/4e/*',
         '.git/objects/50/*',
         '.git/objects/51/*',
         '.git/objects/53/*',
         '.git/objects/56/*',
         '.git/objects/59/*',
         '.git/objects/5a/*',
         '.git/objects/5b/*',
         '.git/objects/5c/*',
         '.git/objects/5d/*',
         '.git/objects/5e/*',
         '.git/objects/60/*',
         '.git/objects/61/*',
         '.git/objects/62/*',
         '.git/objects/64/*',
         '.git/objects/67/*',
         '.git/objects/68/*',
         '.git/objects/69/*',
         '.git/objects/6a/*',
         '.git/objects/6e/*',
         '.git/objects/6f/*',
         '.git/objects/71/*',
         '.git/objects/74/*',
         '.git/objects/75/*',
         '.git/objects/76/*',
         '.git/objects/77/*',
         '.git/objects/78/*',
         '.git/objects/79/*',
         '.git/objects/7b/*',
         '.git/objects/7d/*',
         '.git/objects/82/*',
         '.git/objects/83/*',
         '.git/objects/85/*',
         '.git/objects/86/*',
         '.git/objects/89/*',
         '.git/objects/8d/*',
         '.git/objects/93/*',
         '.git/objects/94/*',
         '.git/objects/95/*',
         '.git/objects/96/*',
         '.git/objects/97/*',
         '.git/objects/98/*',
         '.git/objects/99/*',
         '.git/objects/9b/*',
         '.git/objects/9c/*',
         '.git/objects/9d/*',
         '.git/objects/9e/*',
         '.git/objects/9f/*',
         '.git/objects/a3/*',
         '.git/objects/a5/*',
         '.git/objects/a6/*',
         '.git/objects/a7/*',
         '.git/objects/a8/*',
         '.git/objects/ab/*',
         '.git/objects/ae/*',
         '.git/objects/af/*',
         '.git/objects/b0/*',
         '.git/objects/b1/*',
         '.git/objects/b2/*',
         '.git/objects/b3/*',
         '.git/objects/b8/*',
         '.git/objects/b9/*',
         '.git/objects/ba/*',
         '.git/objects/bc/*',
         '.git/objects/be/*',
         '.git/objects/bf/*',
         '.git/objects/c1/*',
         '.git/objects/c2/*',
         '.git/objects/c3/*',
         '.git/objects/c4/*',
         '.git/objects/c6/*',
         '.git/objects/c7/*',
         '.git/objects/c8/*',
         '.git/objects/cb/*',
         '.git/objects/cc/*',
         '.git/objects/cf/*',
         '.git/objects/d0/*',
         '.git/objects/d2/*',
         '.git/objects/d4/*',
         '.git/objects/d5/*',
         '.git/objects/d6/*',
         '.git/objects/d8/*',
         '.git/objects/dc/*',
         '.git/objects/dd/*',
         '.git/objects/de/*',
         '.git/objects/df/*',
         '.git/objects/e0/*',
         '.git/objects/e1/*',
         '.git/objects/e4/*',
         '.git/objects/e6/*',
         '.git/objects/e7/*',
         '.git/objects/e9/*',
         '.git/objects/eb/*',
         '.git/objects/ec/*',
         '.git/objects/ed/*',
         '.git/objects/ee/*',
         '.git/objects/ef/*',
         '.git/objects/f0/*',
         '.git/objects/f2/*',
         '.git/objects/f3/*',
         '.git/objects/f5/*',
         '.git/objects/f7/*',
         '.git/objects/fb/*',
         '.git/objects/fc/*',
         '.git/objects/fd/*',
         '.git/objects/fe/*',
         '.git/objects/ff/*',
         '.git/objects/pack/*',
         '.git/refs/heads/*',
         '.git/refs/remotes/origin/*',
         'config/clean.yaml']}

install_requires = \
['openai>=0.15.0,<0.16.0',
 'praw>=7.5.0,<8.0.0',
 'pydub>=0.25.1,<0.26.0',
 'rich>=11.2.0,<12.0.0',
 'toml>=0.10.2,<0.11.0']

setup_kwargs = {
    'name': 'robolson',
    'version': '0.3.6',
    'description': 'My collection of utilty scripts',
    'long_description': None,
    'author': 'Rob L Olson',
    'author_email': 'rob.louis@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.10,<4.0',
}


setup(**setup_kwargs)
