# PEP 518: https://www.python.org/dev/peps/pep-0518/

[tool.poetry]
name = "ttls"
version = "1.4.3"
description = "Twinkly Twinkly Little Star"
authors = ["Jakob Schlyter <jakob@schlyter.se>"]
license = "BSD"
readme = "README.md"
repository = "https://github.com/jschlyter/ttls"

[tool.poetry.scripts]
ttls = "ttls.cli:main"

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.3"
colour = "^0.1.5"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest-black = "^0.3.12"
isort = "^5.6.4"
pytest-isort = "^1.2.0"
pytest = "^6.1.2"
pylama = "^7.7.1"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
