[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "goingnats"
authors = [{name = "Eugene Van den Bulke", email = "eugene.vandenbulke@gmail.com"}]
readme = "README.md"
dynamic = ["version", "description"]
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
]

[project.urls]
Home = "https://github.com/3kwa/goingnats"
