
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-25T16:53:10-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "954274e91b063a4819d13d34a18c3006aedac1c3",
 "version": "0.9.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
