[tool.poetry]
name = "koil"
version = "0.1.68"
readme = "README.md"
description = "An abstract event loop to run in an async and sync context (especially jupyter and qt), with utility functions to allow both accesses"
authors = ["jhnnsrs <jhnnsrs@gmail.com>"]
license = "CC BY-NC 3.0"
packages = [{include = "koil"}]

[tool.poetry.dependencies]
python = "^3.7"
jupyter = {version = "^1.0.0", optional = true}
qtpy = {version = ">1", optional = true}

[tool.poetry.extras]
jupyter = ["jupyter"]
qtpy = ["qt"]

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-aiohttp = "^0.3.0"
pytest-cov = "^3.0.0"
black = "^21.12b0"
tox = "^3.24.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
