[project]
name = "rtmidi2"
authors = [
    { name = "Eduardo Moguillansky", email = "eduardo.moguillansky@gmail.com" }
]
license = "MIT"
readme = "README.rst"
requires_python = "^3.8"
homepage = "https://github.com/gesellkammer/rtmidi2"
repository = "https://github.com/gesellkammer/rtmidi2"

dependencies = [
  'numpy>=1.22',
]

classifiers = [
    "Topic :: Software Development"
]

[build-system]

requires = [
    "setuptools>=42",
    "wheel",
    "cython",
    "numpy>=1.22"
]

build-backend = "setuptools.build_meta"

