
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T22:15:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "27978c9e7361390c94cff03961e3e64862968501",
 "version": "v0.3.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
