
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-27T02:17:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9db6e543d6090a3256f20695c1d3224df8cbbc0e",
 "version": "0.9.dev2209"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
