# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import zuper_commons.logs
import types
import constants
import state
import storage
import structures
import exceptions
import progress_imp2
import context
import master
import registrar
import priority
import helpers
import visualization
import uptodate
import parsing
import cachequerydb
import filesystem
import queries
import ui
import actions
import dependencies
import manager
import commands
import colored
import result_dict
import actions_newprocess
import context_imp
import config_ui
import config_list
import readrcfiles
import job_execution
import commands_html
import compmake_plugins
import inspect
import logging
import traceback
import asyncio
import time
import zuper_commons.types
import zuper_utils_asyncio
import utils
import zuper_commons.fs
import zuper_commons.text
import zuper_zapp_interfaces
import contextlib
import zuper_commons.ui
import console
import multiprocessing
import structure
import optparse
import config_html
import future
import interpret
import readline
import pyreadline
import abc
import dataclasses
import aiofiles
import zuper_typing
import events_structures
import copy
import stat
import glob
import os.path
import dill
import collections
import itertools
import shutil
import signal
import warnings
import zuper_commons.cmds
import zuper_zapp
import config_optparse
import cProfile
import pstats
import readcommands
import registered_events
import utils.pickle_frustration
import typing_extensions
import capture
import coloredterm
import docstring
import format_exceptions
import frozen
import instantiate_utils
import memoize_imp
import pickling_utils
import proctitle
import safe_pickle
import strings_with_escapes
import system_stats
import terminal_size
import time_track
import timedate
import values_interpretation
import which_imp
import wildcards
import table_formatter
import io
import termcolor
import pickle
import setproctitle
import psutil
import fcntl
import termios
import struct
import datetime
import re

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

