[tool.poetry]
name = "tfc_utils"
version = "0.0.4"
description = "A helper tool (CLI) for Terraform Cloud"
authors = ["Ilya Sotkov <ilya@sotkov.com>"]

[tool.poetry.dependencies]
python = "^3.8"
terrasnek = "*"
typer = "*"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
black = "^22.1"
pylint = "^2.12"
pylint-pytest = "^1.1"
pytest-cov = "^3.0"
pyright = "0.0.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
known_third_party = ["tfc_utils"]
line_length = 100

[tool.black]
line-length = 100

[tool.pylint.messages_control]
max-line-length = 100
disable = [
  "missing-docstring"
]
good-names = ["e"]
