
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T22:09:18-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "46bb05226961f7a7e8775e47f29dc04b1209bf14",
 "version": "v0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
