[tool.poetry]
name = "parallel_loading"
version = "0.1.0"
description = ""
authors = ["p208p2002 <p208p2002@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
colorama = "^0.4.4"
termcolor = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.6.0"
transformers = "^4.16.2"
torch = "^1.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
