class CuckooFilter:
    @property
    def item_count(self) -> tuple[int, int]: ...
    @property
    def memory_size(self) -> int: ...
    @property
    def victim(self) -> tuple[int, int]: ...
    def __init__(self, max_key_count: int) -> None: ...
    def add(self, key: bytes) -> int: ...
    def contains(self, key: bytes) -> int: ...
    def remove(self, key: bytes) -> int: ...
