
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T14:45:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0f1d27f64a40976fe7bb54bd11b0c3757e685d7",
 "version": "0.19.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
