
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-03T01:18:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "49f3df75d66c16a3f49a32a4b27ce6f88616db91",
 "version": "0.0.67.post0.dev74"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
