
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T16:14:22-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "31f579009f79299c6c867c324baa2dde619ea883",
 "version": "2022.2.24.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
