[build-system]
requires = ["setuptools>=43", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--doctest-modules --doctest-glob='*.rst'"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py3{10,9,8,7,6}
skip_missing_interpreters = true

[testenv]
deps =
    pytest
commands = pytest
"""

[tool.coverage.run]
source = ["src"]

[tool.coverage.html]
directory = "htmlcov"