[project]
name = "mumema"
version = "1.1.1"
description = "Music Metadata Manager"
readme = "./README.md"
requires-python = ">=3.6"
license = { file="./LICENSE" }
authors = [ { name="Johannes Krattenmacher", email="mumema@dev.krateng.ch" } ]

urls.repository = "https://github.com/krateng/mumema"

keywords = ["scripts", "commandline"]
classifiers = [
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
	"Operating System :: OS Independent"
]

dependencies = [
	"doreah >= 1.6.11",
	"unidecode",
]

[project.scripts]
mumema = "mumema:main"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
