[tool.poetry]
name = "os-image-builder"
version = "0.1.4"
description = "Helper for image isos"
authors = ["Martin Ortbauer <mortbauer@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
"ruamel.yaml" = "^0.17.20"
click = "^8.0.3"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
os-image-builder = 'os_image_builder:main'
