[project]
authors = [
    { name = "MrTango", email = "md@derico.de" },
]
dependencies = [
    "accesscontrol==5.2",
    "acquisition==4.9",
    "attrs==21.2.0",
    "authencoding==4.3",
    "beautifulsoup4==4.10.0",
    "borg.localrole==3.1.8",
    "btrees==4.9.2",
    "calmjs.parse==1.2.5",
    "certifi==2021.10.8",
    "cffi==1.15.0",
    "chameleon==3.9.1",
    "charset-normalizer==2.0.7",
    "collective.monkeypatcher==1.2.1",
    "cssselect==1.1.0",
    "datetime==4.3",
    "decorator==5.0.9",
    "diazo==1.4.2",
    "documenttemplate==4.0",
    "docutils==0.17",
    "extensionclass==4.5.1",
    "feedparser==6.0.8",
    "five.customerize==2.0.1",
    "five.intid==1.2.6",
    "five.localsitemanager==3.2.2",
    "future==0.18.2",
    "icalendar==4.0.9",
    "idna==3.3",
    "jsonschema==3.2.0",
    "lxml==4.6.4",
    "markdown==3.3.4",
    "missing==4.1",
    "mockup==4.0.2",
    "multimapping==4.1",
    "multipart==0.2.4",
    "paste==3.5.0",
    "pastedeploy==2.1.1",
    "persistence==3.1",
    "persistent==4.7.0",
    "piexif==1.1.3",
    "pillow==9.0.0",
    "plone==6.0.0a3",
    "plone.alterego==1.1.5",
    "plone.api==2.0.0a2",
    "plone.app.caching==3.0.0a10",
    "plone.app.content==4.0.0a9",
    "plone.app.contentlisting==2.0.6",
    "plone.app.contentmenu==2.3.4",
    "plone.app.contentrules==5.0.0a3",
    "plone.app.contenttypes==3.0.0a9",
    "plone.app.customerize==1.3.11",
    "plone.app.dexterity==3.0.0a7",
    "plone.app.discussion==4.0.0a3",
    "plone.app.event==4.0.0a7",
    "plone.app.i18n==3.0.6",
    "plone.app.intid==1.1.4",
    "plone.app.iterate==4.0.2",
    "plone.app.layout==4.0.0a9",
    "plone.app.linkintegrity==3.5.0",
    "plone.app.locales==6.0.1",
    "plone.app.lockingbehavior==1.0.7",
    "plone.app.multilingual==6.0.0a7",
    "plone.app.portlets==5.0.0a7",
    "plone.app.querystring==1.4.15",
    "plone.app.redirector==2.2.1",
    "plone.app.registry==2.0.0a7",
    "plone.app.relationfield==3.0.0a1",
    "plone.app.textfield==1.3.6",
    "plone.app.theming==5.0.0a4",
    "plone.app.upgrade==3.0.0a3",
    "plone.app.users==3.0.0a5",
    "plone.app.uuid==2.1.0",
    "plone.app.versioningbehavior==1.4.5",
    "plone.app.viewletmanager==3.1.2",
    "plone.app.vocabularies==4.3.0",
    "plone.app.widgets==3.0.6",
    "plone.app.workflow==5.0.0a2",
    "plone.app.z3cform==4.0.0a6",
    "plone.autoform==1.9.0",
    "plone.autoinclude==1.0.0a3",
    "plone.batching==2.0.0a1",
    "plone.behavior==1.4.0",
    "plone.browserlayer==2.2.4",
    "plone.cachepurging==2.0.4",
    "plone.caching==1.2.2",
    "plone.contentrules==2.1.2",
    "plone.dexterity==3.0.0a2",
    "plone.event==1.4.1",
    "plone.folder==3.1.0",
    "plone.formwidget.namedfile==3.0.0a4",
    "plone.formwidget.recurrence==2.1.5",
    "plone.i18n==5.0.0a4",
    "plone.indexer==1.0.7",
    "plone.intelligenttext==3.1.0",
    "plone.keyring==3.1.3",
    "plone.locking==2.2.5",
    "plone.memoize==2.1.1",
    "plone.namedfile==6.0.0a1",
    "plone.outputfilters==4.0.2",
    "plone.portlet.collection==4.0.0a2",
    "plone.portlet.static==4.0.0a1",
    "plone.portlets==2.3.2",
    "plone.protect==4.1.6",
    "plone.registry==1.2.1",
    "plone.resource==2.1.4",
    "plone.resourceeditor==3.0.3",
    "plone.rest==2.0.0a2",
    "plone.restapi==8.21.0",
    "plone.rfc822==2.0.2",
    "plone.scale==3.1.2",
    "plone.schema==1.3.0",
    "plone.schemaeditor==3.0.3",
    "plone.session==3.7.5",
    "plone.staticresources==2.0.0a2",
    "plone.stringinterp==1.3.3",
    "plone.subrequest==1.9.3",
    "plone.supermodel==1.6.4",
    "plone.theme==3.0.7",
    "plone.transformchain==2.0.2",
    "plone.uuid==1.0.6",
    "plone.volto==4.0.0a2",
    "plone.z3cform==2.0.0a1",
    "plonetheme.barceloneta==3.0.0a9",
    "ply==3.11",
    "products.btreefolder2==4.3",
    "products.cmfcore==2.5.4",
    "products.cmfdifftool==3.3.3",
    "products.cmfdynamicviewfti==7.0.0a1",
    "products.cmfeditions==4.0.0a3",
    "products.cmfplacefulworkflow==3.0.0a1",
    "products.cmfplone==6.0.0a3",
    "products.cmfuid==3.2.0",
    "products.daterecurringindex==3.0.1",
    "products.dcworkflow==2.5.0",
    "products.extendedpathindex==4.0.1",
    "products.externalmethod==4.5",
    "products.genericsetup==2.1.5",
    "products.isurlinportal==1.2.1",
    "products.mailhost==4.11",
    "products.mimetypesregistry==2.1.9",
    "products.plonepas==7.0.0a2",
    "products.pluggableauthservice==2.7.0",
    "products.pluginregistry==1.9",
    "products.portaltransforms==3.1.12",
    "products.pythonscripts==4.13",
    "products.sessions==4.12",
    "products.siteerrorlog==5.5",
    "products.standardcachemanagers==4.1.1",
    "products.statusmessages==5.0.5",
    "products.zcatalog==6.1",
    "products.zopeversioncontrol==2.0.0",
    "pycparser==2.21",
    "pyjwt==1.7.1",
    "pyrsistent==0.18.0",
    "pyscss==1.3.7",
    "python-dateutil==2.8.2",
    "python-gettext==4.0",
    "pytz==2021.3",
    "record==3.5",
    "repoze.xmliter==0.6.1",
    "requests==2.26.0",
    "restrictedpython==5.2",
    "roman==3.3",
    "sgmllib3k==1.0.0",
    "simplejson==3.17.3",
    "six==1.16.0",
    "soupsieve==2.3.1",
    "transaction==3.0.1",
    "unidecode==1.2.0",
    "urllib3==1.26.7",
    "waitress==2.0.0",
    "webob==1.8.7",
    "webtest==3.0.0",
    "wsgiproxy2==0.5.1",
    "z3c.caching==2.2",
    "z3c.form==3.7.1",
    "z3c.formwidget.query==0.17",
    "z3c.objpath==1.2",
    "z3c.pt==3.3.0",
    "z3c.relationfield==0.9.0",
    "z3c.zcmlhook==1.1",
    "zc.lockfile==2.0",
    "zc.relation==1.1.post2",
    "zconfig==3.6.0",
    "zdaemon==4.3",
    "zeo==5.2.3",
    "zexceptions==4.2",
    "zodb==5.6.0",
    "zodb3==3.11.0",
    "zodbpickle==2.2.0",
    "zope==5.4",
    "zope.annotation==4.7.0",
    "zope.app.locales==4.1",
    "zope.browser==2.3",
    "zope.browsermenu==4.4",
    "zope.browserpage==4.4.0",
    "zope.browserresource==4.4",
    "zope.cachedescriptors==4.3.1",
    "zope.component==4.6.2",
    "zope.componentvocabulary==2.2.0",
    "zope.configuration==4.4.0",
    "zope.container==4.4.0",
    "zope.contentprovider==4.2.1",
    "zope.contenttype==4.5.0",
    "zope.copy==4.2",
    "zope.datetime==4.3.0",
    "zope.deferredimport==4.3.1",
    "zope.deprecation==4.4.0",
    "zope.dottedname==4.3",
    "zope.event==4.5.0",
    "zope.exceptions==4.4",
    "zope.filerepresentation==5.0.0",
    "zope.globalrequest==1.5",
    "zope.hookable==5.1.0",
    "zope.i18n==4.8.0",
    "zope.i18nmessageid==5.0.1",
    "zope.interface==5.4.0",
    "zope.intid==4.4.0",
    "zope.keyreference==4.2.0",
    "zope.lifecycleevent==4.3",
    "zope.location==4.2",
    "zope.pagetemplate==4.6.0",
    "zope.processlifetime==2.3.0",
    "zope.proxy==4.5.0",
    "zope.ptresource==4.2.0",
    "zope.publisher==6.0.2",
    "zope.ramcache==2.3",
    "zope.schema==6.2.0",
    "zope.security==5.1.1",
    "zope.sendmail==5.2",
    "zope.sequencesort==4.2",
    "zope.site==4.5.0",
    "zope.size==4.3",
    "zope.structuredtext==4.3",
    "zope.tal==4.5",
    "zope.tales==5.1",
    "zope.testbrowser==5.5.1",
    "zope.testing==4.9",
    "zope.traversing==4.4.1",
    "zope.viewlet==4.2.1",
    "zope2==4.0",
    "-e sources/plone.gallery",
    "-e git+ssh://git@github.com/plone/plone.pdfexport.git@main#egg=plone.pdfexport",
]
description = ""
name = "plonedistro.derico"
requires-python = ">=3.8,<3.10"
version = "0.1"

[project.license]
text = "MIT"

[project.urls]
homepage = "http://derico.de"

[tool.pdm]
use_venv = true
source = [
    { name = "pypi", url = "https://pypi.org/simple", verify_ssl = true },
]

[tool.pdm.scripts]
init = "mkwsgiinstance -d instance -u admin:admin"
start = "runwsgi -v etc/zope.ini"

[build-system]
build-backend = "pdm.pep517.api"
requires = [
    "pdm-pep517",
]
