
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <frc/commands/WaitCommand.h>

#include <wpi/sendable/SendableBuilder.h>
#include <frc/commands/Command.h>
#include <frc/commands/CommandGroup.h>



#include <rpygen/frc__TimedCommand.hpp>

namespace rpygen {

using namespace frc;


template <typename CfgBase>
using PyTrampolineCfgBase_frc__WaitCommand =
    PyTrampolineCfg_frc__TimedCommand<
CfgBase
>;

template <typename CfgBase = EmptyTrampolineCfg>
struct PyTrampolineCfg_frc__WaitCommand :
    PyTrampolineCfgBase_frc__WaitCommand< CfgBase>
{
    using Base = frc::WaitCommand;

};


template <typename PyTrampolineBase, typename PyTrampolineCfg>
using PyTrampolineBase_frc__WaitCommand =
    PyTrampoline_frc__TimedCommand<
        PyTrampolineBase
        
        , PyTrampolineCfg
    >
;

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_frc__WaitCommand : PyTrampolineBase_frc__WaitCommand<PyTrampolineBase, PyTrampolineCfg> {
    using PyTrampolineBase_frc__WaitCommand<PyTrampolineBase, PyTrampolineCfg>::PyTrampolineBase_frc__WaitCommand;






};

}; // namespace rpygen
