
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-25T08:21:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "746f34113260e7727b4e03283a9340fcef57d279",
 "version": "2022.2.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
