[package]
name = "vegafusion-core"
version = "0.0.4"
edition = "2021"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
tonic_support = ["tonic", "tonic-build"]

[dependencies]
thiserror = "^1.0.29"
bytes = "1.1.0"
prost = "0.9.0"
prost-types = "0.9.0"
arrow = { version="6.3.0", default_features=false, features=["ipc"] }
datafusion = { version = "6.0.0", optional=true }
pyo3 = { version = "0.15.1", optional=true }
itertools = "0.10.1"
lazy_static = "^1.4.0"
regex = "^1.5.4"
serde = { version="1.0.130", features=["derive"] }
serde_json = "1.0.68"
ordered-float = "^2.8.0"
petgraph = "0.6.0"
deterministic-hash = "1.0.1"
chrono = "0.4.19"
tonic = { version="0.6.1", optional=true }

[build-dependencies]
prost-build = "0.9.0"
tonic-build = { version="0.6.2", optional=true }
