
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-18T17:39:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4dda89890ffe669778354b9752cc47c4fac5f4c4",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
