[tool.poetry]
name = "web3storage"
version = "0.1.1"
description = "Interacting with the web3.storage API to upload/download files"
authors = ["Marcus Weinberger"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
