
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-27T00:08:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "cebaed2f7ae6ae5241ee23844e8fb5ca2748986a",
 "version": "2022.2.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
