[build-system]
requires = [
   'setuptools-git-versioning', 
   'pip>=19.3',
   'setuptools>=57.1.0',
   'wheel>=0.36.2',
   'build>=0.5.1',
   "ninja; platform_machine!='aarch64' and platform_machine != 'arm64'",
   'cmake >= 3.20.5',
   ]
build-backend = "setuptools.build_meta"
