[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
include_trailing_comma = true
ensure_newline_before_comments = true
known_first_party = "anaplan"

[tool.black]
line-length = 120
target-version = ['py38']
