[tool.poetry]
name = "maaml"
version = "0.4.9"
description = "For time series datasets Machine learning pipline"
authors = ["Najemeddine Abdennour"]
license = "GNU General Public License v3 (GPLv3)"

[tool.poetry.dependencies]
python = "^3.6"
pandas = "^1.3"
numpy = "^1.22.0"
sklearn = "^0.0"
keras = "^2.7"
matplotlib ="^3.4"
fastparquet="^0.8.0"
xgboost="^1.5.2"
tensorflow="^2.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
