[tool.poetry]
name = "xlsx-lib-infomoto"
version = "0.8.4"
description = ""
authors = ["tomasdarioam <tomasdarioam@protonmail.com>"]
packages = [
    { include = "./**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.9"
openpyxl = "^3.0.7"
openpyxl-image-loader = "^1.0.5"
pydantic = "^1.8.2"
python-camel-model-infomoto = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
