[tool.poetry]
name = "pycordrest"
version = "0.1.0"
description = "The REST API for py-cord"
authors = ["InfiniteCore"]
license = "MIT"
repository = "https://github.com/InfiniteCore/pycordrest"
readme = "README.md"
keywords = ["discord", "rest"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.3"
py-cord = "^1.7.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
