[tool.poetry]
name = "dis-snek"
version = "7.0.0"
description = "An API wrapper for Discord filled with snakes"
authors = ["LordOfPolls <ddavidallen13@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.7.4"
attrs = "^21.2.0"
mypy = "^0.910"
discord-typings = "^0.2.2"
tomli = "1.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0", "tomli"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
