
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-28T18:54:35-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7d79934a34edbce53a882646b84d1814d133151",
 "version": "v4.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
