[tool.black]
line-length = 130
target_version = ["py310"]
include = '''
(
    ^/tests/.*[.]py$
  | ^/mb_waves/.*[.]py$
  | ^/setup[.]py
)
'''
exclude = '''
(
     __pycache__
     | ^/.venv
     | ^/.mypy_cache
     | ^/*.egg-info
     | ^/build
     | ^/dist
)
'''

[tool.isort]
line_length = 130
use_parentheses = "True"
include_trailing_comma = "True"
multi_line_output = 3
default_section = "THIRDPARTY"
known_first_party = "mb_waves"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.mypy]
python_version = "3.10"
warn_no_return = false

[tool.pytest.ini_options]
addopts = "-n auto"
markers = { infura = "requires access to infura servers", ws_node = "requires a private WS_NODE", web = "http requests" }
