
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-02T00:42:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a8aedbc873bbd891ee8d500ca74a3ab186640fe0",
 "version": "1.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
