
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <frc/buttons/PressedButtonScheduler.h>

#include <wpi/sendable/SendableBuilder.h>
#include <frc/buttons/Trigger.h>
#include <frc/commands/Command.h>
#include <frc/commands/CommandGroup.h>



#include <rpygen/frc__ButtonScheduler.hpp>

namespace rpygen {

using namespace frc;


template <typename CfgBase>
using PyTrampolineCfgBase_frc__PressedButtonScheduler =
    PyTrampolineCfg_frc__ButtonScheduler<
CfgBase
>;

template <typename CfgBase = EmptyTrampolineCfg>
struct PyTrampolineCfg_frc__PressedButtonScheduler :
    PyTrampolineCfgBase_frc__PressedButtonScheduler< CfgBase>
{
    using Base = frc::PressedButtonScheduler;

    using override_base_Execute_v = frc::PressedButtonScheduler;
};


template <typename PyTrampolineBase, typename PyTrampolineCfg>
using PyTrampolineBase_frc__PressedButtonScheduler =
    PyTrampoline_frc__ButtonScheduler<
        PyTrampolineBase
        
        , PyTrampolineCfg
    >
;

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_frc__PressedButtonScheduler : PyTrampolineBase_frc__PressedButtonScheduler<PyTrampolineBase, PyTrampolineCfg> {
    using PyTrampolineBase_frc__PressedButtonScheduler<PyTrampolineBase, PyTrampolineCfg>::PyTrampolineBase_frc__PressedButtonScheduler;



#ifndef RPYGEN_DISABLE_Execute_v
    void Execute() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_Execute_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "execute", );
        return CxxCallBase::Execute();
    }
#endif




};

}; // namespace rpygen
