[tool.poetry]
name = "damnsshmanager"
version = "0.2.4"
description = "The simplest ssh cli agent one is able to find"
authors = ["Nils Verheyen <nils@ungerichtet.de>"]
license = "GNU GPLv3"
packages = [{include = 'damnsshmanager'}]

[tool.poetry.scripts]
dsm = 'damnsshmanager.cli:main'

[tool.poetry.dependencies]
python = "^3.8"
loguru = "^0.5.3"
appdirs = "^1.4.4"
paramiko = "^2.8.0"
sshtunnel = "^0.4.0"

[tool.poetry.dev-dependencies]
ipython = "^7.30.1"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pylint = "^2.12.2"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
