
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-23T17:46:10-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "3435d6e823616563fcde7d2e81023ca3b1fc38eb",
 "version": "v0.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
