[tool.poetry]
name = "file_grouper"
version = "0.1.1"
description = "Group file based on file name pattern defined by regex."
authors = ["Yu Wang <anselmwang@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
keyring = "^23.5.0"
artifacts-keyring = "^0.3.1"
twine = "^3.8.0"
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.poetry.scripts]
hello = 'file_grouper.console:hello'
group_file = 'file_grouper.file_grouper:group_file'