
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-25T09:17:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5738d1d6618efe624dc244e0e629c8ebffea8c0a",
 "version": "2604"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
