
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T14:46:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4b0a23a8a297243c19592bf0eaaf5d0454ea8d1",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
