
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-25T11:11:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b47ed70f2fc1a12b68aac81907c7312b3a3e3a7",
 "version": "2605"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
