
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-01T17:47:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b921202c4909f113c5e0ce8a3e3fea2bc7627b24",
 "version": "0.0.67.post0.dev62"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
