
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T11:54:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a08dfb9eede57f16e6da67bddd91ce3c74e2ab3",
 "version": "1.1.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
