
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-01T14:02:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0885b6b1d5067c0d5fbd5dc9c5a75f1514f8db7a",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
