[tool.poetry]
name = "calculate_future_date"
version = "0.1.0"
description = ""
authors = ["pratik kumar sarangi <psarangi50@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"
Flask = "2.0.3"

[tool.poetry.scripts]
my_calc="calculate_future_date.mycalc:calc_future"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
