
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T07:07:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "661e7d75aacbffecf4c087d7660f32ad7d11dac3",
 "version": "0.0.65.post0.dev157"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
