
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-26T08:23:18-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e448376e32b5aae867ca16b694c080d46e370e9a",
 "version": "0.1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
