[tool.poetry]
name = "barsdiary"
version = "0.0.2-alpha"
description = "Python library for working with API \"БАРС.Web-Образование\""
license = "MIT"
readme = "README.md"
authors = ["mironovmeow <71277890+mironovmeow@users.noreply.github.com>"]
homepage = "https://github.com/mironovmeow/barsdiary"
repository = "https://github.com/mironovmeow/barsdiary"
# documentation = "https://barsdiary.readthedocs.io/ru/latest/"
keywords = [
    "python",
    "aiohttp",
    "pydantic",
    "asyncio",
]
exclude = [
    "barsdiary/tests/**",
    ".github/**",
    ".flake8",
    ".gitignore",
    ".pre-commit-config.yaml",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/mironovmeow/barsdiary/issues"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.9.0"
loguru = "^0.6.0"
requests = "^2.27.1"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
flake8 = "^4.0.1"
mypy = "^0.931"
pytest = "^7.0.0"
isort = "^5.10.1"
black = "^22.1.0"
types-requests = "^2.27.11"

[tool.isort]
line_length = 99
include_trailing_comma = true
multi_line_output = 3

[tool.mypy]
warn_unused_configs = true

[tool.black]
line-length = 99


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
