
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-01T13:59:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a7777a97fcf1f9ee4f0ee3feb32c09d8af9d77c",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
