
# This file was generated by 'versioneer.py' (0.20.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-27T23:13:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "352f942aa31d2cf12e8e3beef7491d7555674f9e",
 "version": "0.15.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
