[tool.poetry]
name = "broadway"
version = "0.1.4"
description = ""
authors = ["jfwu-ai <junfeng.wu@ainnocence.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
