[tool.poetry]
name = "leap-model-parser"
version = "0.1.2"
description = ""
authors = ["idan <idan.yogev@tensorleap.ai>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tensorleap/leap-model-parser"
homepage = "https://github.com/tensorleap/leap-model-parser"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.6.1,<3.7"
tensorflow = "2.4.4"
numpy = "^1.19.5"
onnx = "1.6.0"
onnx2kerastl = "0.0.32"
keras-data-format-converter = "0.0.4"
tensorflow-io-gcs-filesystem = "0.21.0"
tensorflow-addons = "0.14.0"

dataclasses = "0.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
grappa = "^1.0.1"
pytest-cov = "^3.0.0"
pytest-watch = "^4.2.0"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = ["ignore:.*the imp module.*:DeprecationWarning"]