
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-02T21:37:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a90d91138e78a7c9ea80867ef5852d4a4d0c4006",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
