
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T15:44:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d52cb4c42c9fd1107bb20f031bd27b3ddbd24727",
 "version": "0.9.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
