# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pcas/keyvalue/_condition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pcas.keyvalue import _value_pb2 as pcas_dot_keyvalue_dot___value__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pcas/keyvalue/_condition.proto',
  package='kvdb',
  syntax='proto3',
  serialized_options=b'Z\t.;kvdbrpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1epcas/keyvalue/_condition.proto\x12\x04kvdb\x1a\x1apcas/keyvalue/_value.proto\"/\n\x0eManyConditions\x12\x1d\n\x04\x63ond\x18\x01 \x03(\x0b\x32\x0f.kvdb.Condition\"*\n\x07LhsBool\x12\x0b\n\x03lhs\x18\x01 \x01(\t\x12\x12\n\nbool_value\x18\x02 \x01(\x08\"8\n\rLhsManyValues\x12\x0b\n\x03lhs\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x03(\x0b\x32\x0b.kvdb.Value\"T\n\rLhsLowerUpper\x12\x0b\n\x03lhs\x18\x01 \x01(\t\x12\x1a\n\x05lower\x18\x02 \x01(\x0b\x32\x0b.kvdb.Value\x12\x1a\n\x05upper\x18\x03 \x01(\x0b\x32\x0b.kvdb.Value\"\xad\x01\n\x0cLeafOperator\x12\x0b\n\x03lhs\x18\x01 \x01(\t\x12+\n\x06opcode\x18\x02 \x01(\x0e\x32\x1b.kvdb.LeafOperator.LeafType\x12\x18\n\x03rhs\x18\x03 \x01(\x0b\x32\x0b.kvdb.Value\"I\n\x08LeafType\x12\r\n\tUNDEFINED\x10\x00\x12\x06\n\x02\x45Q\x10\x01\x12\x06\n\x02NE\x10\x02\x12\x06\n\x02GT\x10\x03\x12\x06\n\x02LT\x10\x04\x12\x06\n\x02GE\x10\x05\x12\x06\n\x02LE\x10\x06\"\xc0\x03\n\tCondition\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.kvdb.Condition.CondType\x12\x35\n\x15many_conditions_value\x18\x02 \x01(\x0b\x32\x14.kvdb.ManyConditionsH\x00\x12\x34\n\x15lhs_lower_upper_value\x18\x03 \x01(\x0b\x32\x13.kvdb.LhsLowerUpperH\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x12\x34\n\x15lhs_many_values_value\x18\x05 \x01(\x0b\x32\x13.kvdb.LhsManyValuesH\x00\x12(\n\nleaf_value\x18\x06 \x01(\x0b\x32\x12.kvdb.LeafOperatorH\x00\x12\'\n\x0elhs_bool_value\x18\x07 \x01(\x0b\x32\r.kvdb.LhsBoolH\x00\"v\n\x08\x43ondType\x12\r\n\tUNDEFINED\x10\x00\x12\x07\n\x03\x41ND\x10\x01\x12\x0b\n\x07\x42\x45TWEEN\x10\x02\x12\x08\n\x04\x42OOL\x10\x03\x12\x06\n\x02IN\x10\x04\x12\x08\n\x04LEAF\x10\x05\x12\x0e\n\nNOTBETWEEN\x10\x06\x12\t\n\x05NOTIN\x10\x07\x12\x06\n\x02OR\x10\x08\x12\x06\n\x02IS\x10\tB\x07\n\x05valueB\x0bZ\t.;kvdbrpcb\x06proto3'
  ,
  dependencies=[pcas_dot_keyvalue_dot___value__pb2.DESCRIPTOR,])



_LEAFOPERATOR_LEAFTYPE = _descriptor.EnumDescriptor(
  name='LeafType',
  full_name='kvdb.LeafOperator.LeafType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EQ', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=406,
  serialized_end=479,
)
_sym_db.RegisterEnumDescriptor(_LEAFOPERATOR_LEAFTYPE)

_CONDITION_CONDTYPE = _descriptor.EnumDescriptor(
  name='CondType',
  full_name='kvdb.Condition.CondType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AND', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BETWEEN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BOOL', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IN', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEAF', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOTBETWEEN', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOTIN', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OR', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IS', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=803,
  serialized_end=921,
)
_sym_db.RegisterEnumDescriptor(_CONDITION_CONDTYPE)


_MANYCONDITIONS = _descriptor.Descriptor(
  name='ManyConditions',
  full_name='kvdb.ManyConditions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cond', full_name='kvdb.ManyConditions.cond', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=115,
)


_LHSBOOL = _descriptor.Descriptor(
  name='LhsBool',
  full_name='kvdb.LhsBool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lhs', full_name='kvdb.LhsBool.lhs', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='kvdb.LhsBool.bool_value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=159,
)


_LHSMANYVALUES = _descriptor.Descriptor(
  name='LhsManyValues',
  full_name='kvdb.LhsManyValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lhs', full_name='kvdb.LhsManyValues.lhs', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='kvdb.LhsManyValues.value', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=217,
)


_LHSLOWERUPPER = _descriptor.Descriptor(
  name='LhsLowerUpper',
  full_name='kvdb.LhsLowerUpper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lhs', full_name='kvdb.LhsLowerUpper.lhs', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lower', full_name='kvdb.LhsLowerUpper.lower', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper', full_name='kvdb.LhsLowerUpper.upper', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=303,
)


_LEAFOPERATOR = _descriptor.Descriptor(
  name='LeafOperator',
  full_name='kvdb.LeafOperator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lhs', full_name='kvdb.LeafOperator.lhs', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opcode', full_name='kvdb.LeafOperator.opcode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rhs', full_name='kvdb.LeafOperator.rhs', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LEAFOPERATOR_LEAFTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=479,
)


_CONDITION = _descriptor.Descriptor(
  name='Condition',
  full_name='kvdb.Condition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='kvdb.Condition.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='many_conditions_value', full_name='kvdb.Condition.many_conditions_value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lhs_lower_upper_value', full_name='kvdb.Condition.lhs_lower_upper_value', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='kvdb.Condition.bool_value', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lhs_many_values_value', full_name='kvdb.Condition.lhs_many_values_value', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leaf_value', full_name='kvdb.Condition.leaf_value', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lhs_bool_value', full_name='kvdb.Condition.lhs_bool_value', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONDITION_CONDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='kvdb.Condition.value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=482,
  serialized_end=930,
)

_MANYCONDITIONS.fields_by_name['cond'].message_type = _CONDITION
_LHSMANYVALUES.fields_by_name['value'].message_type = pcas_dot_keyvalue_dot___value__pb2._VALUE
_LHSLOWERUPPER.fields_by_name['lower'].message_type = pcas_dot_keyvalue_dot___value__pb2._VALUE
_LHSLOWERUPPER.fields_by_name['upper'].message_type = pcas_dot_keyvalue_dot___value__pb2._VALUE
_LEAFOPERATOR.fields_by_name['opcode'].enum_type = _LEAFOPERATOR_LEAFTYPE
_LEAFOPERATOR.fields_by_name['rhs'].message_type = pcas_dot_keyvalue_dot___value__pb2._VALUE
_LEAFOPERATOR_LEAFTYPE.containing_type = _LEAFOPERATOR
_CONDITION.fields_by_name['type'].enum_type = _CONDITION_CONDTYPE
_CONDITION.fields_by_name['many_conditions_value'].message_type = _MANYCONDITIONS
_CONDITION.fields_by_name['lhs_lower_upper_value'].message_type = _LHSLOWERUPPER
_CONDITION.fields_by_name['lhs_many_values_value'].message_type = _LHSMANYVALUES
_CONDITION.fields_by_name['leaf_value'].message_type = _LEAFOPERATOR
_CONDITION.fields_by_name['lhs_bool_value'].message_type = _LHSBOOL
_CONDITION_CONDTYPE.containing_type = _CONDITION
_CONDITION.oneofs_by_name['value'].fields.append(
  _CONDITION.fields_by_name['many_conditions_value'])
_CONDITION.fields_by_name['many_conditions_value'].containing_oneof = _CONDITION.oneofs_by_name['value']
_CONDITION.oneofs_by_name['value'].fields.append(
  _CONDITION.fields_by_name['lhs_lower_upper_value'])
_CONDITION.fields_by_name['lhs_lower_upper_value'].containing_oneof = _CONDITION.oneofs_by_name['value']
_CONDITION.oneofs_by_name['value'].fields.append(
  _CONDITION.fields_by_name['bool_value'])
_CONDITION.fields_by_name['bool_value'].containing_oneof = _CONDITION.oneofs_by_name['value']
_CONDITION.oneofs_by_name['value'].fields.append(
  _CONDITION.fields_by_name['lhs_many_values_value'])
_CONDITION.fields_by_name['lhs_many_values_value'].containing_oneof = _CONDITION.oneofs_by_name['value']
_CONDITION.oneofs_by_name['value'].fields.append(
  _CONDITION.fields_by_name['leaf_value'])
_CONDITION.fields_by_name['leaf_value'].containing_oneof = _CONDITION.oneofs_by_name['value']
_CONDITION.oneofs_by_name['value'].fields.append(
  _CONDITION.fields_by_name['lhs_bool_value'])
_CONDITION.fields_by_name['lhs_bool_value'].containing_oneof = _CONDITION.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['ManyConditions'] = _MANYCONDITIONS
DESCRIPTOR.message_types_by_name['LhsBool'] = _LHSBOOL
DESCRIPTOR.message_types_by_name['LhsManyValues'] = _LHSMANYVALUES
DESCRIPTOR.message_types_by_name['LhsLowerUpper'] = _LHSLOWERUPPER
DESCRIPTOR.message_types_by_name['LeafOperator'] = _LEAFOPERATOR
DESCRIPTOR.message_types_by_name['Condition'] = _CONDITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ManyConditions = _reflection.GeneratedProtocolMessageType('ManyConditions', (_message.Message,), {
  'DESCRIPTOR' : _MANYCONDITIONS,
  '__module__' : 'pcas.keyvalue._condition_pb2'
  # @@protoc_insertion_point(class_scope:kvdb.ManyConditions)
  })
_sym_db.RegisterMessage(ManyConditions)

LhsBool = _reflection.GeneratedProtocolMessageType('LhsBool', (_message.Message,), {
  'DESCRIPTOR' : _LHSBOOL,
  '__module__' : 'pcas.keyvalue._condition_pb2'
  # @@protoc_insertion_point(class_scope:kvdb.LhsBool)
  })
_sym_db.RegisterMessage(LhsBool)

LhsManyValues = _reflection.GeneratedProtocolMessageType('LhsManyValues', (_message.Message,), {
  'DESCRIPTOR' : _LHSMANYVALUES,
  '__module__' : 'pcas.keyvalue._condition_pb2'
  # @@protoc_insertion_point(class_scope:kvdb.LhsManyValues)
  })
_sym_db.RegisterMessage(LhsManyValues)

LhsLowerUpper = _reflection.GeneratedProtocolMessageType('LhsLowerUpper', (_message.Message,), {
  'DESCRIPTOR' : _LHSLOWERUPPER,
  '__module__' : 'pcas.keyvalue._condition_pb2'
  # @@protoc_insertion_point(class_scope:kvdb.LhsLowerUpper)
  })
_sym_db.RegisterMessage(LhsLowerUpper)

LeafOperator = _reflection.GeneratedProtocolMessageType('LeafOperator', (_message.Message,), {
  'DESCRIPTOR' : _LEAFOPERATOR,
  '__module__' : 'pcas.keyvalue._condition_pb2'
  # @@protoc_insertion_point(class_scope:kvdb.LeafOperator)
  })
_sym_db.RegisterMessage(LeafOperator)

Condition = _reflection.GeneratedProtocolMessageType('Condition', (_message.Message,), {
  'DESCRIPTOR' : _CONDITION,
  '__module__' : 'pcas.keyvalue._condition_pb2'
  # @@protoc_insertion_point(class_scope:kvdb.Condition)
  })
_sym_db.RegisterMessage(Condition)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
