# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pcas/keyvalue/_sort.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pcas/keyvalue/_sort.proto',
  package='kvdb',
  syntax='proto3',
  serialized_options=b'Z\t.;kvdbrpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19pcas/keyvalue/_sort.proto\x12\x04kvdb\"\x1e\n\tDirection\x12\x11\n\tdirection\x18\x01 \x01(\x08\"8\n\x05Order\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\tdirection\x18\x02 \x01(\x0b\x32\x0f.kvdb.Direction\"%\n\x07OrderBy\x12\x1a\n\x05order\x18\x01 \x03(\x0b\x32\x0b.kvdb.OrderB\x0bZ\t.;kvdbrpcb\x06proto3'
)




_DIRECTION = _descriptor.Descriptor(
  name='Direction',
  full_name='kvdb.Direction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='kvdb.Direction.direction', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=65,
)


_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='kvdb.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kvdb.Order.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='direction', full_name='kvdb.Order.direction', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=123,
)


_ORDERBY = _descriptor.Descriptor(
  name='OrderBy',
  full_name='kvdb.OrderBy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='order', full_name='kvdb.OrderBy.order', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=162,
)

_ORDER.fields_by_name['direction'].message_type = _DIRECTION
_ORDERBY.fields_by_name['order'].message_type = _ORDER
DESCRIPTOR.message_types_by_name['Direction'] = _DIRECTION
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
DESCRIPTOR.message_types_by_name['OrderBy'] = _ORDERBY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Direction = _reflection.GeneratedProtocolMessageType('Direction', (_message.Message,), {
  'DESCRIPTOR' : _DIRECTION,
  '__module__' : 'pcas.keyvalue._sort_pb2'
  # @@protoc_insertion_point(class_scope:kvdb.Direction)
  })
_sym_db.RegisterMessage(Direction)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'pcas.keyvalue._sort_pb2'
  # @@protoc_insertion_point(class_scope:kvdb.Order)
  })
_sym_db.RegisterMessage(Order)

OrderBy = _reflection.GeneratedProtocolMessageType('OrderBy', (_message.Message,), {
  'DESCRIPTOR' : _ORDERBY,
  '__module__' : 'pcas.keyvalue._sort_pb2'
  # @@protoc_insertion_point(class_scope:kvdb.OrderBy)
  })
_sym_db.RegisterMessage(OrderBy)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
