
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-01T16:29:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "15708c153d68f9291813e602bf825a2a3e90d1b1",
 "version": "1.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
