[build-system]
requires = [
    "Beaker",
    "Cython>=0.20",
    "compyle>=0.8",
    "cyarray",
    "mako",
    "oldest-supported-numpy",
    "pytools",
    "setuptools>=42.0.0",
    "wheel>=0.29.0",
]