# Generated by Django 3.0.7 on 2021-01-28 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npl_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='portfoliosnapshot',
            name='user',
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='counterparty_group_identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='npl_portfolio.CounterpartyGroup'),
        ),
    ]
