# Generated by Django 3.1.8 on 2021-06-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl_portfolio', '0004_auto_20210314_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='distribution_made_to_the_seller',
            field=models.BooleanField(blank=True, help_text='https://www.openriskmanual.org/wiki/EBA_NPL.Counterparty.Distribution_made_to_the_Seller. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.Counterparty.Country_of_Registered_Location">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='notice_for_procedure_termination',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether the notice of the end of the procedure has been given to the seller. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.Counterparty.Notice_for_Procedure_Termination">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='proof_of_claim_filed_by_the_seller',
            field=models.BooleanField(blank=True, help_text='Proof of Claim Filed by the seller. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.Counterparty.Proof_of_Claim_Filed_by_the_seller">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='enforcement',
            name='indicator_of_enforcement',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether the Enforcement process has been entered into by a Corporate or Private Individual Counterparty. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.Enforcement.Indicator_of_Enforcement">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='enforcement',
            name='indicator_of_receivership',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether the Corporate or Private Individual Counterparty is in Receivership. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.Enforcement.Indicator_of_Receivership">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='enforcement',
            name='insurance',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether the receiver has insured the Property / Collateral. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.Enforcement.Insurance">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='externalcollection',
            name='repayment_plan',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether a repayment plan has been agreed with the external collection agency. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.External Collection.Repayment_Plan">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='forbearance',
            name='clause_to_stop_forbearance',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether a clause exists to allow the Institution to stop the current forbearance. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.Forbearance.Clause_to_Stop_Forbearance">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='marp_applicable',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether the Institution operates a Mortgage Arrears Resolution Process when dealing with Corporates or Private Individual Counterparties in Mortgage Arrears. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.Loan.MARP_Applicable">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='recourse_to_other_assets',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether the Institution has the legal right to access other assets of the Borrower. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.Loan.Recourse_to_Other_Assets">Documentation</a>', null=True),
        ),
    ]
