# Generated by Django 3.1.8 on 2021-06-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl_portfolio', '0005_auto_20210607_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonpropertycollateral',
            name='activation_of_guarantee',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether the guarantee has been activated when "Guarantee" is selected in field "Collateral Type". <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.NonProperty Collateral.Activation_of_Guarantee">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='nonpropertycollateral',
            name='asset_purchase_obligation',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether there is an obligation for the Borrower to purchase the Collateral at the end of the lease. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.NonProperty_Collateral.Asset_Purchase_Obligation">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='nonpropertycollateral',
            name='collateral_insurance',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether there is an insurance on the Collateral. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.NonProperty Collateral.Collateral_Insurance">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='nonpropertycollateral',
            name='enforcement_status',
            field=models.BooleanField(blank=True, help_text='Status of the enforcement process that the Collateral is currently in as at cut-off date, e.g. if it is in receivership. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.NonProperty Collateral.Enforcement_Status">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='nonpropertycollateral',
            name='enforcement_status_third_parties',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether any other secured creditors have taken steps to enforce security over the asset? (Y/N). <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.NonProperty Collateral.Enforcement_Status_Third_Parties">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='propertycollateral',
            name='completion_of_property',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether the construction of the Unit is complete. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.Property Collateral.Completion_of_Property">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='propertycollateral',
            name='enforcement_status',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether the property collateral has entered into the enforcement process as at cut-off date. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.Property Collateral.Enforcement_Status">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='propertycollateral',
            name='enforcement_status_third_parties',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether any other secured creditors have taken steps to enforce security over the asset? (Y/N). <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.Property Collateral.Enforcement_Status_Third_Parties">Documentation</a>', null=True),
        ),
        migrations.AlterField(
            model_name='propertycollateral',
            name='vat_payable',
            field=models.BooleanField(blank=True, help_text='Indicator as to whether the VAT is payable on the disposal of the Unit. <a class="risk_manual_url" href="https://www.openriskmanual.org/wiki/EBA_NPL.Property Collateral.VAT_Payable">Documentation</a>', null=True),
        ),
    ]
