
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-26T12:55:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7bc9d35181fd641d21573af687009efc05e4d34",
 "version": "v1.5.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
