# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.struct_pb2 import (
    Struct as google___protobuf___struct_pb2___Struct,
)

from ondewo.nlu.context_pb2 import (
    Context as ondewo___nlu___context_pb2___Context,
)

from ondewo.nlu.intent_pb2 import (
    Intent as ondewo___nlu___intent_pb2___Intent,
)

from ondewo.nlu.session_pb2 import (
    EventInput as ondewo___nlu___session_pb2___EventInput,
    QueryResult as ondewo___nlu___session_pb2___QueryResult,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class PingRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    session = ... # type: typing___Text

    def __init__(self,
        *,
        session : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> PingRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> PingRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"session",b"session"]) -> None: ...
global___PingRequest = PingRequest

class WebhookRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    session = ... # type: typing___Text
    response_id = ... # type: typing___Text

    @property
    def query_result(self) -> ondewo___nlu___session_pb2___QueryResult: ...

    @property
    def original_detect_intent_request(self) -> global___OriginalDetectIntentRequest: ...

    @property
    def headers(self) -> google___protobuf___struct_pb2___Struct: ...

    def __init__(self,
        *,
        session : typing___Optional[typing___Text] = None,
        response_id : typing___Optional[typing___Text] = None,
        query_result : typing___Optional[ondewo___nlu___session_pb2___QueryResult] = None,
        original_detect_intent_request : typing___Optional[global___OriginalDetectIntentRequest] = None,
        headers : typing___Optional[google___protobuf___struct_pb2___Struct] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> WebhookRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> WebhookRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"headers",b"headers",u"original_detect_intent_request",b"original_detect_intent_request",u"query_result",b"query_result"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"headers",b"headers",u"original_detect_intent_request",b"original_detect_intent_request",u"query_result",b"query_result",u"response_id",b"response_id",u"session",b"session"]) -> None: ...
global___WebhookRequest = WebhookRequest

class WebhookResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    fulfillment_text = ... # type: typing___Text
    source = ... # type: typing___Text

    @property
    def fulfillment_messages(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ondewo___nlu___intent_pb2___Intent.Message]: ...

    @property
    def payload(self) -> google___protobuf___struct_pb2___Struct: ...

    @property
    def output_contexts(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ondewo___nlu___context_pb2___Context]: ...

    @property
    def followup_event_input(self) -> ondewo___nlu___session_pb2___EventInput: ...

    def __init__(self,
        *,
        fulfillment_text : typing___Optional[typing___Text] = None,
        fulfillment_messages : typing___Optional[typing___Iterable[ondewo___nlu___intent_pb2___Intent.Message]] = None,
        source : typing___Optional[typing___Text] = None,
        payload : typing___Optional[google___protobuf___struct_pb2___Struct] = None,
        output_contexts : typing___Optional[typing___Iterable[ondewo___nlu___context_pb2___Context]] = None,
        followup_event_input : typing___Optional[ondewo___nlu___session_pb2___EventInput] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> WebhookResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> WebhookResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"followup_event_input",b"followup_event_input",u"payload",b"payload"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"followup_event_input",b"followup_event_input",u"fulfillment_messages",b"fulfillment_messages",u"fulfillment_text",b"fulfillment_text",u"output_contexts",b"output_contexts",u"payload",b"payload",u"source",b"source"]) -> None: ...
global___WebhookResponse = WebhookResponse

class OriginalDetectIntentRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    source = ... # type: typing___Text

    @property
    def payload(self) -> google___protobuf___struct_pb2___Struct: ...

    def __init__(self,
        *,
        source : typing___Optional[typing___Text] = None,
        payload : typing___Optional[google___protobuf___struct_pb2___Struct] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> OriginalDetectIntentRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> OriginalDetectIntentRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"payload",b"payload"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"payload",b"payload",u"source",b"source"]) -> None: ...
global___OriginalDetectIntentRequest = OriginalDetectIntentRequest

class PingResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    is_reachable = ... # type: builtin___bool

    def __init__(self,
        *,
        is_reachable : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> PingResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> PingResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"is_reachable",b"is_reachable"]) -> None: ...
global___PingResponse = PingResponse
