[tool.poetry]
name = "lateco"
version = "0.2.0"
description = "A framework for creating, managing and analysing large text corpora"
authors = ["Thomas Zastrow <post@thomas-zastrow.de>"]

[tool.poetry.dependencies]
python = "^3.7"
elasticsearch = "^7.16.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
