
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-02T10:00:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9e93d681363399cb3da0fcb2bce70c36ce5169df",
 "version": "2610"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
