[package]
name = "pycddl"
version = "0.1.10"  # pycddl version, for bumpversion
edition = "2021"
license = "MIT"
authors = ["Tahoe-LAFS project"]
description = "Validate CBOR documents using CDDL schema language"
homepage = "https://gitlab.com/tahoe-lafs/pycddl"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pycddl"
crate-type = ["cdylib"]

[dependencies]
cddl = "0.9.0-beta.0"

[dependencies.serde_json]
features = ["std"]

[dependencies.pyo3]
version = "0.15"
features = ["extension-module"]
