
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-25T22:40:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9b442867748be6376446f1bdd85fecc4fca0476",
 "version": "1.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
