# Generated by Django 4.0.2 on 2022-02-24 06:51

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='group.name')),
            ],
            options={
                'verbose_name': 'group.verbose',
                'verbose_name_plural': 'group.plural',
            },
        ),
        migrations.CreateModel(
            name='GroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=settings.LANGUAGES, max_length=32, verbose_name='group_item.language')),
                ('key', models.CharField(max_length=256, verbose_name='group_item.key')),
                ('translate', models.CharField(max_length=256, verbose_name='group_item.translate')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='django_locales.group', verbose_name='group.verbose')),
            ],
            options={
                'verbose_name': 'group_item.verbose',
                'verbose_name_plural': 'group_item.plural',
            },
        ),
        migrations.AddConstraint(
            model_name='groupitem',
            constraint=models.UniqueConstraint(fields=('language', 'key'), name='unique_key'),
        ),
    ]
