
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-01T15:28:10-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "afb32f6640bb059c5cf2a0d2bc46e46b219b5a57",
 "version": "4.7.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
