
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-28T11:08:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d14cdcb86ce027ae780cd8575d48aad9e9e0c1d",
 "version": "0.7.1.post.dev397"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
