---
- name: upgrade to Debian GNU/Linux bullseye
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Set Debian GNU/Linux bullseye repositories
      copy:
        dest: /etc/apt/sources.list
        content: |
          deb http://deb.debian.org/debian/ bullseye main
          deb http://deb.debian.org/debian/ buster main
          deb http://security.debian.org/debian-security bullseye-security main
          deb http://security.debian.org/debian-security buster/updates main
          deb http://deb.debian.org/debian bullseye-backports main
      when: '"debian" == ansible_user'

    - name: Debian/Ubuntu | Installing repository key
      apt_key: url=https://packages.wazuh.com/key/GPG-KEY-WAZUH

    - name: Run the equivalent of "apt-get update"
      shell: |
        apt-get --allow-releaseinfo-change update

    #
    # The old configuration will be discarded but restored by the next run
    # of the playbooks.
    #
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        dpkg_options: force-confnew

