[tool.poetry]
name = "randalyze"
version = "0.1.2"
description = "Create series of random numbers fitting a specified distribution, and then analyze them."
authors = ["Jason Ross (big-jr) <jason@softwarepragmatism.com>"]
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
nose2 = "0.11.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
randalyze = "randalyze.__main__:main"
