[tool.briefcase]
project_name = "Maestral"
bundle = "com.samschott"
version = "1.6.0.dev1"
url = "https://maestral.app"
license = "MIT license"
author = "Sam Schott"
author_email = "sam.schott@outlook.com"

[tool.briefcase.app.maestral-cocoa]
formal_name = "Maestral"
description = "An open-source Dropbox client for macOS and Linux"
icon = "icon/maestral"
sources = ["src/maestral_cocoa"]
requires = [
    "bugsnag",
    "click",
    "importlib_metadata;python_version<'3.8'",
    "importlib_resources;python_version<'3.9'",
    "maestral@git+https://github.com/samschott/maestral",
    "markdown2",
    "rubicon-objc>=0.4.1",
    "toga==0.3.0.dev30",
]
template = "https://github.com/samschott/briefcase-macOS-Xcode-template"
template_branch = "maestral"

[tool.briefcase.app.maestral-cocoa.macOS]
agent = 1
requires = [
    "toga-cocoa>=0.3.0.dev25",
]

[tool.briefcase.app.maestral-cocoa.linux]
requires = [
    "toga-gtk>=0.3.0.dev25",
]
system_requires = [
    "libgirepository1.0-dev",
    "libcairo2-dev",
    "libpango1.0-dev",
    "libwebkitgtk-3.0-0",
    "gir1.2-webkit-3.0",
]

[tool.black]
line-length = 88
target-version = ["py36", "py37", "py38", "py39"]
extend-exclude = 'macOS/(.*?)'

[build-system]
requires = ["setuptools>=41.0", "wheel"]
build-backend = "setuptools.build_meta"
