[tool.poetry]
name = "sfctools"
version = "0.4.1"
description =   "Framework for stock-flow consistent agent-based modeling, being developed at the German Aerospace Center (DLR) for and in the scientific context of energy systems analysis, however, it is widely applicable in other scientific fields."

authors = ["Thomas Baldauf, Benjamin Fuchs <thomas.baldauf@dlr.de, benjamin.fuchs@dlr.de>"]
license = "MIT"
maintainers = ["Thomas Baldauf <thomas.baldauf@dlr.de>"]
homepage = 'https://gitlab.com/dlr-ve/esy/sfctools'
documentation = 'https://pypi.org/project/sfctools/'
readme = 'README.md'
keywords = ["stock-flow-consistent","agent-based","agent","macroeconomics","computational economics"]

packages = [
    { include = "sfctools" },
]


[tool.poetry.dependencies]
python = "^3.6"
pandas = "^1.0"
numpy = "^1.20.1"
setuptools = "^60.0.0"
poetry = "^1.1.6"
wheel = "^0.36.2"
pip = "^21.1.1"
attrs = "19.3.0"
cattrs = "1.0.0"
matplotlib = "^3.4"
pyyaml = "^6.0"
seaborn = "^0.11.2"
networkx = "^2.6.3"
graphviz = "^0.19"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
