# PEP 518: https://www.python.org/dev/peps/pep-0518/

[tool.isort]
profile = "black"

[tool.poetry]
name = "wapi2nsconf"
version = "0.4.0"
description = "Infoblox WAPI to DNS server configuration tool"
authors = ["Jakob Schlyter <jakob@kirei.se>"]
license = "BSD"

[tool.poetry.scripts]
wapi2nsconf = "wapi2nsconf.cli:main"

[tool.poetry.dependencies]
Jinja2 = "^3.0.3"
python = "^3.7"
PyYAML = "^5.3.1"
requests = "^2.25.0"
urllib3 = "^1.26.2"
voluptuous = "^0.12.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.4"
pylama = "^7.7.1"
pytest = "^6.1.2"
pytest-black = "^0.3.12"
pytest-isort = "^1.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
