[project]
name = "fsclean"
version = "1.0.0"
description = "Tool to clean up filenames"
readme = "./README.md"
requires-python = ">=3.6"
license = { file="./LICENSE" }
authors = [ { name="Johannes Krattenmacher", email="fsclean@dev.krateng.ch" } ]

urls.repository = "https://github.com/krateng/fsclean"

keywords = ["scripts", "commandline"]
classifiers = [
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
	"Operating System :: OS Independent"
]

dependencies = [
	"emoji",
	"unidecode",
	"doreah"
]

[project.scripts]
fsclean =	"fsclean:main"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
