
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-03T03:08:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "aafb71ffe3f850e22b9745d181ab956d96ff75bf",
 "version": "0.0.67.post0.dev76"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
