[tool.poetry]
name = "dj-datatables-view"
version = "0.1.8"
description = "Django datatables view fork from django-datatables-view"
readme = "README.rst"
authors = ["Longbowou <blandedaniel@gmail.com>"]
maintainers = ["Longbowou <blandedaniel@gmail.com>"]
homepage = 'https://gitlab.com/longbowou/django-datatables-view'
repository = 'https://gitlab.com/longbowou/django-datatables-view'
keywords = ["django", "datatable", "view"]
license = 'MIT'

[tool.poetry.urls]
"Bug Tracker" = "https://gitlab.com/longbowou/django-datatables-view/issues"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
