
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T14:34:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "95b4d03337e9315d3c595cecac598a1aa275d3a5",
 "version": "2600"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
