
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T10:40:53-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "0a38b16167c105b3aadde914822738b5e4a64def",
 "version": "3.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
