from setuptools import setup
from pathlib import Path
long_description = Path("./README.md").read_text()

setup(
  name='jft',
  version='0.0.26',
  license='MIT',
  description='Function Test Pair Toolbox',
  long_description=long_description,
  long_description_content_type="text/markdown",
  author='@JohnRForbes',
  author_email='john.robert.forbes@gmail.com',
  url='https://gitlab.com/zereiji/jft',
  packages=[
    'jft',
    'jft/directory',
    'jft/dict',
    'jft/dicts',
    'jft/directories',
    'jft/directory',
    'jft/fake',
    'jft/file',
    'jft/file/pyfile',
    'jft/files',
    'jft/function',
    'jft/lists',
    'jft/patch',
    'jft/pickle',
    'jft/pip',
    'jft/pyfiles',
    'jft/report',
    'jft/schedule',
    'jft/setup',
    'jft/string',
    'jft/strings',
    'jft/subprocess',
    'jft/system',
    'jft/test',
    'jft/text_colours',
  ],
  keywords='jft',
  install_requires=[],
)
