
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T10:51:20-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6ad7624a9bc014bb22620e99bbde22c0b074f34",
 "version": "1.5.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
