
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-01T19:03:28-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "41b5cadaafc00be7fbe36b2fca176087974bf32c",
 "version": "2022.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
