
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-24T09:00:27-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "b5e69f5a2055f3f5f4c9e23305cbdc91171ed7ec",
 "version": "1.18.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
