
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-02T16:35:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7fb6a573c8b8613087ab085966daddd6a16fed05",
 "version": "0.0.67.post0.dev70"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
