
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-01T01:13:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ab946da0da779cefe09ae07f658c611d1109dc7f",
 "version": "0.0.67.post0.dev58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
