
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <frc/pidwrappers/PIDAnalogInput.h>




#include <rpygen/frc__PIDSource.hpp>
#include <rpygen/frc__AnalogInput.hpp>

namespace rpygen {

using namespace frc;


template <typename CfgBase>
using PyTrampolineCfgBase_frc__PIDAnalogInput =
    PyTrampolineCfg_frc__PIDSource<
    PyTrampolineCfg_frc__AnalogInput<
CfgBase
>>;

template <typename CfgBase = EmptyTrampolineCfg>
struct PyTrampolineCfg_frc__PIDAnalogInput :
    PyTrampolineCfgBase_frc__PIDAnalogInput< CfgBase>
{
    using Base = frc::PIDAnalogInput;

    using override_base_PIDGet_v = frc::PIDAnalogInput;
};


template <typename PyTrampolineBase, typename PyTrampolineCfg>
using PyTrampolineBase_frc__PIDAnalogInput =
    PyTrampoline_frc__PIDSource<
    PyTrampoline_frc__AnalogInput<
        PyTrampolineBase
        
        , PyTrampolineCfg
    >
        
        , PyTrampolineCfg
    >
;

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_frc__PIDAnalogInput : PyTrampolineBase_frc__PIDAnalogInput<PyTrampolineBase, PyTrampolineCfg> {
    using PyTrampolineBase_frc__PIDAnalogInput<PyTrampolineBase, PyTrampolineCfg>::PyTrampolineBase_frc__PIDAnalogInput;



#ifndef RPYGEN_DISABLE_PIDGet_v
    double PIDGet() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_PIDGet_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(double), LookupBase,
            "PIDGet", );
        return CxxCallBase::PIDGet();
    }
#endif




};

}; // namespace rpygen
