
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-02T14:35:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7dd38a73bed4b02e279b6e19757ca2e49cc3b72d",
 "version": "1.37.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
