
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-01T16:14:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "228393b33c2a818f80dbe68c1c58549434041d2c",
 "version": "0.1.0a56"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
