[tool.poetry]
name = "xontrib-pyenv"
version = "1.1.0"
description = "Skeleton for `xontrib-pyenv`. This package is deprecated, please use `xontrib-langenv` instead."
authors = ["Gyuri Horak <dyuri@horak.hu>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/dyuri/xontrib-pyenv"
classifiers=[
    'Environment :: Console',
    'Programming Language :: Python',
    'Topic :: System :: Shells',
    'Topic :: System :: System Shells',
]

[tool.poetry.dependencies]
python = "^3.6"
xontrib-langenv = "^1.0.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
