[tool.poetry]
name = "sinagot"
version = "0.5.1"
description = "Python lightweight workflow management framework with data exploration features"
authors = ["Yann Beauxis <pro@yannbeauxis.net>"]
maintainers = ["Yann Beauxis <pro@yannbeauxis.net>"]
license = "BSD-2-Clause"
readme = "README.md"
homepage = "https://gitlab.com/YannBeauxis/sinagot"
repository = "https://gitlab.com/YannBeauxis/sinagot"
documentation = "https://gitlab.com/YannBeauxis/sinagot"

[tool.poetry.dependencies]
python = "^3.8"
networkx = "^2.6.3"
ray = "^1.9.1"
pandas = "^1.3.5"

matplotlib = { version = "^3.5.1", optional = true }
pydot = { version = "^1.4.2", optional = true }
pydantic = "^1.9.0"

[tool.poetry.extras]
draw = ["numpy", "matplotlib", "pydot"]


[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
black = "^21.5b2"
rope = "^0.19.0"
pylint = "^2.8.3"
flake8 = "^4.0.1"
mypy = "^0.910"
types-setuptools = "^57.4.2"
pytest-cov = "^3.0.0"
pytest-datadir = "^1.3.1"
ipykernel = "^6.6.1"
ray = {extras = ["default"], version = "^1.9.1"}
pytest-env = "^0.6.2"

[tool.poetry.scripts]
test = "tests.cli:run"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
