[tool.poetry]
name = "my-repos"
version = "0.1.1"
description = "Keep an offline mirror of some git repositories"
authors = ["xtofl <kristoffel.pirard@gmail.com>"]
license = "LGPL"
packages = [
    {include = "myrepos", from="src"},
]

[tool.poetry.scripts]
my-repos = "myrepos.repos:cli"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
