[tool.poetry]
name = "CSNTM-toolbox"
version = "0.1.0"
description = ""
authors = ["David Flood <davidfloodii@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
prepify = "^0.5.0"
NameWiz = "^0.1.0"
ManuscriptMonitor = "^0.1.0"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
