[tool.poetry]
name = "skime"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "~2.7"
PyYAML = "^5"

[tool.poetry.dev-dependencies]
nose = "^1.3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
