[tool.poetry]
name = "d2b-nth-of-type"
version = "1.0.1"
description = "Plugin for the d2b package to deterministically uniquify different acquisition runs"
authors = ["Andrew Ross <andrew.ross.mail@gmail.com>"]

readme = "README.md"

keywords = ["neuroscience", "neuroimaging", "bids"]

homepage = "https://github.com/d2b-dev/d2b-nth-of-type"
repository = "https://github.com/d2b-dev/d2b-nth-of-type"
documentation = "https://github.com/d2b-dev/d2b-nth-of-type"

classifiers = [
    "Environment :: Console",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
d2b = "^1.4.0rc1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"
pylint = "^2.12.2"
reorder-python-imports = "^2.7.1"
pre-commit = "^2.17.0"
bump2version = "^1.0.1"
pytest = "^7.0.1"

[tool.poetry.plugins.d2b]
"nth_of_type" = "d2b_nth_of_type"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
