"""
@generated by codestare-proto-plus.  Do not edit manually!
isort:skip_file
"""
import proto
from proto import (
    Field,
    INT32,
)

from proto.message import (
    Message,
)

from ubii.proto.v1.dataStructure.buttonEventType_pb_plus import (
    ButtonEventType,
)


__protobuf__ = proto.module(
    package="ubii.proto.v1",
    manifest={
        "MouseEvent",
    }
)


class MouseEvent(Message):
    type = Field(
        ButtonEventType,
        number=1,
    )
    button = Field(
        INT32,
        number=2,
    )


