
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-02T12:56:31-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "15c55a3dbb6c1bdafa02f486e2070056be6326c9",
 "version": "2.4.0.dev20220303"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
