[dependencies]
async-lock = "2.4.0"
async-recursion = "0.3.2"
async-trait = "0.1.51"
bytes = "1.1.0"
chrono = "0.4.19"
float-cmp = "0.9.0"
futures = "0.3.17"
futures-util = "0.3.17"
itertools = "0.10.1"
lazy_static = "^1.4.0"
lru = "0.7.0"
num-traits = "0.2.14"
prost = "0.9.0"
prost-types = "0.9.0"
regex = "^1.5.4"
serde_json = "1.0.68"
tempfile = "3.2.0"

[dependencies.datafusion]
version = "6.0.0"

[dependencies.reqwest]
default_features = false
features = ["rustls-tls"]
version = "0.11.4"

[dependencies.serde]
features = ["derive"]
version = "1.0.126"

[dependencies.time]
features = ["local-offset"]
version = "0.3.7"

[dependencies.tokio]
features = ["macros", "rt-multi-thread"]
version = "1.10.1"

[dependencies.vegafusion-core]
features = ["datafusion"]
path = "../vegafusion-core"
version = "0.0.4"

[dev-dependencies]
base64 = "0.13.0"
dssim = "3.1.0"
futures = "0.3.17"
futures-util = "0.3.17"
lodepng = "3.4.6"
rgb = "0.8.27"
rstest = "0.11.0"
test-case = "1.2.1"

[dev-dependencies.reqwest]
default_features = false
features = ["blocking", "rustls-tls"]
version = "0.11.4"

[package]
edition = "2021"
license = "AGPL-3.0-or-later"
name = "vegafusion-rt-datafusion"
version = "0.0.4"
