[tool.poetry]
name = "jsonTXeditor"
version = "0.1.0"
description = "a tool for editing JSON-formatted transcriptions files"
authors = ["David Flood <davidfloodii@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
PySimpleGUI = "^4.57.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
