
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-21T09:42:49-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "d962b7b829d5f8ff7cd50e1111d5e852d8fca426",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
